services:
  identidock:
    build: .
    expose:
      - "9090"
    environment:
      ENV: DEV
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster

  redis:
    image: redis:7.2.3
